# Generated by Django 4.2.7 on 2024-01-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drink',
            new_name='Task',
        ),
    ]
