# Generated by Django 5.0.4 on 2024-04-26 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_task_title_alter_task_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='discription',
            new_name='description',
        ),
    ]
